source "https://rubygems.org"

# Jekyll and GitHub Pages gem
gem "github-pages", group: :jekyll_plugins

# Minimal Mistakes dependencies
gem "jekyll-include-cache" # Required for minimal-mistakes theme
